Update to wrap attributes, vertex and particle
Adding these headers compiles fine, but gives an error at load time:

➜  HepMC3.jl git:(main) ✗ julia --project=. test/fourvector.jl
C++ exception while wrapping module HepMC3: No appropriate factory for type e
ERROR: LoadError: No appropriate factory for type e

Which is very strange - "e" is a method, which works perfectly
well when only wrapping the 4-vector header and classes